package main

import (
	"context"
	"encoding/json"
	"fmt"
	"math/rand"
	"time"

	"github.com/ManogyaDahal/DistQ/pkg/client"
)

type Producer struct {
	distqClient *client.Client
	cfg         *AppConfig
}

func NewProducer(distqClient *client.Client, cfg *AppConfig) *Producer {
	return &Producer{
		distqClient: distqClient,
		cfg:         cfg,
	}
}

// Start generates random tasks at regular intervals.
func (p *Producer) Start(ctx context.Context) {
	fmt.Println("Starting Random Task Producer...")

	for {
		// Calculate random interval between Min and Max
		diff := p.cfg.TaskIntervalMax - p.cfg.TaskIntervalMin
		interval := p.cfg.TaskIntervalMin
		if diff > 0 {
			interval += time.Duration(rand.Int63n(int64(diff)))
		}

		select {
		case <-ctx.Done():
			return
		case <-time.After(interval):
			p.submitRandomTask(ctx)
		}
	}
}

func (p *Producer) submitRandomTask(ctx context.Context) {
	// Pick a random task type to submit. Increase probability of webhooks (2)
	choices := []int{1, 2, 2, 2, 2, 3, 4}
	choice := choices[rand.Intn(len(choices))]

	switch choice {
	case 1:
		p.submitStandardTask(ctx)
	case 2:
		p.submitWebhookTask(ctx)
	case 3:
		p.submitFailingTask(ctx)
	case 4:
		// Slightly lower probability for scheduled/cron to avoid spamming them
		if rand.Float32() > 0.5 {
			p.submitScheduledTask(ctx)
		} else {
			p.submitStandardTask(ctx)
		}
	}
}

func (p *Producer) submitStandardTask(ctx context.Context) {
	// We'll use demo.print or demo.sleep built-in handlers
	isSleep := rand.Float32() > 0.5
	taskType := "demo.print"
	priority := 5
	payloadStr := `{"message": "Standard print task generated by test_app"}`

	if isSleep {
		taskType = "demo.sleep"
		priority = 1
		payloadStr = `{"message": "Background sleep task generated by test_app", "seconds": 15}`
	}

	req := client.SubmitTaskRequest{
		Name:     fmt.Sprintf("random-%s", taskType),
		Type:     taskType,
		Priority: priority,
		Payload:  json.RawMessage(payloadStr),
	}

	resp, err := p.distqClient.SubmitTask(ctx, req)
	if err != nil {
		fmt.Printf(" [PRODUCER ERROR] Failed to submit %s: %v\n", taskType, err)
		return
	}
	fmt.Printf(" [PRODUCER] Submitted task %q (ID: %s, Priority: %d)\n", req.Type, resp.ID, resp.Priority)
}

func (p *Producer) submitWebhookTask(ctx context.Context) {
	// Send to our own webhook receiver
	isOrder := rand.Float32() > 0.5
	url := fmt.Sprintf("%s/webhook/notification", p.cfg.WebhookHost)
	body := map[string]any{"alert": "You have a new message", "user_id": 123}

	if isOrder {
		url = fmt.Sprintf("%s/webhook/order-created", p.cfg.WebhookHost)
		body = map[string]any{"order_id": fmt.Sprintf("ORD-%d", rand.Intn(9999)), "total": 49.99}
	}

	req := client.WebhookRequest{
		Name:     "webhook-demo",
		URL:      url,
		Method:   "POST",
		Priority: 10, // Webhooks are high priority in this demo
		Body:     body,
	}

	resp, err := p.distqClient.SubmitWebhook(ctx, req)
	if err != nil {
		fmt.Printf(" [PRODUCER ERROR] Failed to submit webhook: %v\n", err)
		return
	}
	fmt.Printf(" [PRODUCER] Submitted Webhook task (ID: %s, URL: %s)\n", resp.ID, url)
}

func (p *Producer) submitFailingTask(ctx context.Context) {
	// We can use demo.fail built-in or our failing webhook
	useWebhook := rand.Float32() > 0.5

	if useWebhook {
		url := fmt.Sprintf("%s/webhook/failing-endpoint", p.cfg.WebhookHost)
		maxRetries := 2 // Fail fast so we can see it in DLQ quickly

		req := client.WebhookRequest{
			Name:       "failing-webhook",
			URL:        url,
			MaxRetries: &maxRetries,
			Body:       map[string]any{"data": "this will fail"},
		}
		resp, err := p.distqClient.SubmitWebhook(ctx, req)
		if err != nil {
			fmt.Printf(" [PRODUCER ERROR] Failed to submit failing webhook: %v\n", err)
			return
		}
		fmt.Printf(" [PRODUCER] Submitted Failing Webhook task (ID: %s) - will retry %d times\n", resp.ID, maxRetries)
	} else {
		maxRetries := 1
		req := client.SubmitTaskRequest{
			Name:       "failing-demo",
			Type:       "demo.fail",
			MaxRetries: &maxRetries,
			Payload:    json.RawMessage(`{"message": "This task is designed to fail and go to DLQ"}`),
		}
		resp, err := p.distqClient.SubmitTask(ctx, req)
		if err != nil {
			fmt.Printf(" [PRODUCER ERROR] Failed to submit demo.fail: %v\n", err)
			return
		}
		fmt.Printf(" [PRODUCER] Submitted Failing demo.fail task (ID: %s) - will retry %d times\n", resp.ID, maxRetries)
	}
}

func (p *Producer) submitScheduledTask(ctx context.Context) {
	// ETA 15 seconds from now
	eta := time.Now().Add(15 * time.Second)
	req := client.SubmitTaskRequest{
		Name:    "scheduled-report",
		Type:    "demo.print",
		ETA:     &eta,
		Payload: json.RawMessage(`{"message": "Scheduled report generation executing now"}`),
	}

	resp, err := p.distqClient.SubmitTask(ctx, req)
	if err != nil {
		fmt.Printf(" [PRODUCER ERROR] Failed to submit scheduled task: %v\n", err)
		return
	}
	fmt.Printf(" [PRODUCER] Submitted Scheduled task (ID: %s, ETA: %v)\n", resp.ID, req.ETA.Format(time.TimeOnly))
}

func (p *Producer) SubmitCronJob(ctx context.Context) {
	// Cron job every minute
	req := client.SubmitTaskRequest{
		Name:     "minutely-health-check",
		Type:     "demo.print",
		CronExpr: "*/1 * * * *",
		Payload:  json.RawMessage(`{"message": "Executing minutely health check cron job"}`),
	}

	resp, err := p.distqClient.SubmitTask(ctx, req)
	if err != nil {
		fmt.Printf(" [PRODUCER ERROR] Failed to submit cron job: %v\n", err)
		return
	}
	fmt.Printf(" [PRODUCER] Submitted Cron Job task (ID: %s, Expr: %s)\n", resp.ID, req.CronExpr)
}
